- name: play level variables
  hosts: local
  connection: local
  vars: 
   COURSE: Devops
   DURATION: 130HRS
   TRAINER: Shini
  tasks:
  - name: print variables
    ansible.builtin.debug:
     msg: "coursr is {{ COURSE }}, Trainer is {{ TRAINER }}, Duration is {{ DURATION }} "

