- name: print username and password
  hosts: local
  connection: local
  vars_prompt:
   ansible.builtin.debug:
    - name: username
      msg: please enter username
      prompt: rani
      private: false
    - name: password
      msg: please enter password
      prompt: 1234
      private: true
       
   