- name: variable preference
  hosts: local
  connection: local
  # vars:
  #  NAME: "ansible from play"
  # vars_files:
  #   - course.yaml
  # vars_prompt:
    # - name: NAME
    #   prompt: please enter name
    #   private: false
  tasks:
   - name: print from 
    #  vars:
    #   NAME: ansible from tasks
     ansible.builtin.debug:
      msg: "Hi {{ NAME }}"

  #Args
  #Tasks   
  #files 
  #prompt
  #play    
  #inventory