- name: variable preference
  hosts: local
  connection: local
  vars:
   NAME: "ansible form play"
  vars_files:
    - course.yaml
  vars_prompt:
    - name: ansible from prompt
      prompt: please enter name
      private: false
  tasks:
   - name: print from 
    #  vars:
    #   NAME: ansible from tasks
     ansible.builtin.debug:
      msg: "Hi {{ NAME }}"
      
