- name: Print ansible facts 
  hosts: local
  connection: local    
  tasks:
   - name: is ansible sessions more than 6  
     ansible.builtin.debug:
      msg: "{{ ansible_facts }}"
  #  - name: check redhar or not 
  #    ansible.builtin.debug:
  #      msg: ansible_facts.
      